### PR TITLE
first implementation of weighted average linkage

### PR DESCRIPTION
**Pull request by tyrcho**
for #9 

To be reviewed ... I did not test it in details yet.

### CODE REVIEW

**Comment by tyrcho** [comment]
Found a good reference doc on the topic : ([PowerPoint](http://cseweb.ucsd.edu/~maackerman/WeightClusteringSanDiego.pptx))

The first tests are positive, now I need to check it works for my use case also :)

**Comment by lbehnke** [comment]
Did some refactoring to get the interfaces straight. Obviously, a bit too much. Weighted algorithm test is broken. Probably is minor issue. Can you take a look at it?

**Comment by tyrcho** [comment]
Well I found an issue in the master branch, which is fixed by ce45273

But it was a regression I introduced.

I don't see your refactoring about interfaces, did you share it in a branch?

**Comment by tyrcho** [comment]
OK, I think I see the issue, I'll try to solve it today.

**Comment by tyrcho** [comment]
would you please publish a release to maven central with this new feature ?

**Pull request merged**
